image: node:8

before_script:

compile:
  script:
    - ./views/compileviews.sh

test:
  script:
    - docker rm `docker ps -aq`
    - cd views/tests
    - npm install -g purescript
    - npm install -g pulp bower
    - npm i
    - bower i
    - npm test
