image: registry.gitlab.com/hybrix/hybrixd/base-images/build-image:stable

variables:

  KUBERNETES_VERSION: 1.13.12
  HELM_VERSION: 2.14.3

  DOCKER_DRIVER: overlay2

  GIT_STRATEGY: none

#TODO Reset order
stages:
  - build
  - test
  - release
  - deploy

hybrixd:
  cache: {}
  stage: build
  script:
    # Because of race conditions with merge squashes leaving broken references we circumvent the default git strategy GIT_STRATEGY: none
    - cd ..
    - "git clone -n https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/hybrix/hybrixd/node.git --depth 10 --single-branch --branch $CI_COMMIT_REF_NAME"
    - cd node
    - if git log | grep $CI_COMMIT_SHA; then
    -   echo "[i] Commit $CI_COMMIT_SHA exists, retrieving it."
    -   "git -c advice.detachedHead=false checkout $CI_COMMIT_SHA"
    - else
    -   echo "[i] Commit $CI_COMMIT_SHA does not exist, retrieving latest in branch $CI_COMMIT_REF_NAME"
    -   "git checkout"
    - fi
    - sh ./scripts/pipeline/build.sh
  artifacts:
    paths:
    - ./

test:
  stage: test
  script:
     - sh ./scripts/pipeline/test.sh
  coverage: /SUCCESS RATE[^|]*\:[^|]*\s+([\d\.]+)/
  except:
   refs:
     - tags
  only:
    variables:
      - $TEST_ENABLED
  artifacts:
    reports:
      junit: test*.xml

dist:
  dependencies:
    - hybrixd
  stage: release
  script:
    - sh ./scripts/pipeline/dist.sh
  only:
    refs:
      - tags
  artifacts:
    paths:
      - ./

public_build_test:
  stage: test
  script:
     - sh ./scripts/pipeline/public_build_test.sh
  coverage: /SUCCESS RATE[^|]*\:[^|]*\s+([\d\.]+)/
  only:
   refs:
     - tags
  artifacts:
    reports:
      junit: test*.xml

publish:
  cache: {}
  dependencies:
    - hybrixd
  stage: release
  script:
    - sh ./scripts/pipeline/publish.sh
  only:
    refs:
      - tags

deploy:
  cache: {}
  dependencies:
    - dist
  stage: deploy
  allow_failure: false
  script:
    - VERSION_COMMIT="$CI_COMMIT_REF_NAME"
    - echo "[i] Bumping cluster version to $VERSION_COMMIT"
    - "VERSION_COMMIT_BASE64=$(echo $VERSION_COMMIT | base64)"
    - "curl --location --request PUT --header \"PRIVATE-TOKEN: $HYBRIX_BOT_GITLAB_CLUSTER_PUBLISH_WRITE_TOKEN\" \"https://www.gitlab.com/api/v4/projects/16837143/repository/files/version?branch=master&encoding=base64&author_email=bot%40hybrix.io&author_name=hybrix-bot&commit_message=bump%20version%20to%20$VERSION_COMMIT\" --data-urlencode \"content=$VERSION_COMMIT_BASE64\""
  only:
    refs:
      - tags
