image: node:8

hybridd:
  stage: build
  script:
    # install unzip
    - apt-get update
    - apt-get  -y install npm
    - npm install -g jsdoc
    - apt-get install unzip
    
    # trigger pipeline common
    # - "curl --request POST --form \"token=$CI_JOB_TOKEN\" --form ref=master https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/trigger/pipeline"
    
    # download [common] artifact
    - "curl --location --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/jobs/artifacts/master/download?job=common\" -o artifacts-common.zip"
    
    # remove link to common and unzip the downloaded artifact to the directory (|| true --> on error, no problem)
    - rm -rf  common || true
    - unzip -o artifacts-common.zip -d common
    
    # remove the zip-file (|| true --> on error, no problem)
    - rm -rf  artifacts-common.zip || true
    
    # download [interface] artifact
    - "curl --location --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Finterface/jobs/artifacts/master/download?job=interface\" -o artifacts-interface.zip"
    
    # remove link to interface and unzip the downloaded artifact to the directory (|| true --> on error, no problem)
    - rm -rf  interface || true
    - unzip -o artifacts-interface.zip -d interface
    
    # download [deterministic] artifact
    - "curl --location --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fclient%2Fmodules%2Fdeterministic/jobs/artifacts/master/download?job=deterministic\" -o artifacts-deterministic.zip"
    
    # unzip the downloaded artifact to the directory (|| true --> on error, no problem) (consider the artifact is packed as /modules/name/filename.lzma)
    - unzip -o artifacts-deterministic.zip -d artifacts-deterministic/
    - cp -rf artifacts-deterministic/modules/* modules/deterministic/
    
    # remove the unzipped-files and the zip-file (|| true --> on error, no problem)
    - rm -rf  artifacts-deterministic || true
    - rm -rf  artifacts-deterministic.zip || true
    
    # remove symbolic link to node
    - rm -rf  node || true
    # don't download git clone https://github.com/internetofcoins/nodejs-v8-lts.git, refer to docker pre installed nodejs as defined in the first line of this file
    - "ln -s \"$(which nodejs)\" node"
    
    # run the build-script of the hybridd-node
    - ./scripts/npm/build.sh
    
    # clean up and prepare the artifacts (instead of having a dist) 
    # remove everything except () is extglob syntax, which should be enabled first
    # - shopt -s extglob
    # - rm -rf !(dist) || true
    # - mv ./dist/* ./
    # - rm -rf ./dist || true
    
  artifacts:
    paths:
    - ./