before_script:

compile:
  script:
    - ./views/compileviews.sh

test:
  script:
    - ls -l
    - cd tests
    - npm install -g purescript
    - npm install -g pulp bower
    - npm i
    - bower i
    - npm test
